name: jmw
favicon: null
layout_spectrum: 0.9404842928051949
typography_spectrum: 0.5099479728378356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2765615526586771
  lightness: 0.5456927057821304
  saturation: 0.375725268619135
  rhythmicContrast: 0.6318722637370229
purpose: []
